/* ------------------------ TABELAS ------------------------ */
CREATE TABLE EMPRESA
(
	ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	UF VARCHAR(3) NOT NULL,
	NOMEFANTASIA VARCHAR(100) NOT NULL,
	CNPJ VARCHAR(14) NOT NULL,
	CONSTRAINT CadastroMultiplo UNIQUE (CNPJ)	
); 

CREATE TABLE FORN_PJ
(
	ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	NOMEFANTASIA VARCHAR(100) NOT NULL,
	CNPJ VARCHAR(14) NOT NULL,
	DATA_CADASTRO DATETIME,
	TELEFONE VARCHAR (13) NOT NULL,
	CONSTRAINT CadastroPjMultiplo UNIQUE (CNPJ),
	FK_EMP INT NOT NULL	FOREIGN KEY REFERENCES EMPRESA(ID) ON UPDATE CASCADE ON DELETE CASCADE
); 

CREATE TABLE FORN_PF
(
	ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	DATA_CADASTRO DATETIME,
	TELEFONE VARCHAR (13) NOT NULL,
	RG VARCHAR(9),
	NASCIMENTO DATE,
	CONSTRAINT CadastroPfMultiplo UNIQUE (CPF),
	FK_EMP INT NOT NULL	FOREIGN KEY REFERENCES EMPRESA(ID) ON UPDATE CASCADE ON DELETE CASCADE
); 

CREATE TABLE TELEFONES_ADICIONAIS
(
	ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	TELEFONE VARCHAR (13) NOT NULL,
	CONSTRAINT TelefoneExistente UNIQUE (TELEFONE),
	FK_PJ INT FOREIGN KEY REFERENCES FORN_PJ(ID),
	FK_PF INT FOREIGN KEY REFERENCES FORN_PF(ID)
); 


/* ------------------------ BUSCAS PF ------------------------ */
CREATE OR ALTER PROC VerRegistrosPF @EMP INT, @ID INT AS BEGIN
SELECT PF.ID,
	   PF.NOME,
	   PF.CPF,
	   PF.DATA_CADASTRO,
	   PF.TELEFONE,
	   TAD.TELEFONE AS TEL_ADICIONAIS,
	   PF.RG,
	   PF.NASCIMENTO
	   FROM dbo.FORN_PF AS PF 	   
	   INNER JOIN dbo.TELEFONES_ADICIONAIS AS TAD ON TAD.FK_PF = @ID
	   WHERE PF.FK_EMP = @EMP;
END; 

CREATE OR ALTER PROC FiltrarPF @Emp int, @busca varchar(100) AS BEGIN
SELECT * FROM dbo.FORN_PF AS PF	   
	     WHERE PF.FK_EMP = @EMP AND PF.DATA_CADASTRO LIKE '%' + @busca +'%' OR PF.NOME LIKE '%' + @busca +'%' OR PF.CPF LIKE '%' + @busca +'%'
		 ORDER BY PF.ID;	   
END;

/* ------------------------ BUSCAS PJ ------------------------ */

CREATE OR ALTER PROC VerRegistrosPJ @EMP INT, @ID INT AS BEGIN
SELECT PJ.ID,
	   PJ.NOMEFANTASIA,
	   PJ.CNPJ,
	   PJ.DATA_CADASTRO,
	   PJ.TELEFONE,
	   TAD.TELEFONE AS TEL_ADICIONAIS
	   FROM dbo.FORN_PJ AS PJ
	   INNER JOIN dbo.TELEFONES_ADICIONAIS AS TAD ON TAD.FK_PJ = @ID
	   WHERE PJ.FK_EMP = @EMP;
END;

CREATE OR ALTER PROC FiltrarPJ @Emp int, @Busca varchar (100) AS BEGIN
SELECT * FROM dbo.FORN_PJ AS PJ
		 WHERE PJ.FK_EMP = @Emp AND PJ.DATA_CADASTRO LIKE '%' + @busca +'%' OR PJ.NOMEFANTASIA LIKE '%' + @busca +'%' OR PJ.CNPJ LIKE '%' + @busca +'%'
		 ORDER BY PJ.ID
END;

/* ------------------------ INSERT ------------------------ */

CREATE OR ALTER PROC InserirEmpresa @uf varchar(2), @nm varchar(30), @cnpj varchar(14) AS BEGIN
INSERT INTO dbo.EMPRESA (UF, NOMEFANTASIA, CNPJ ) VALUES (@UF, @NM, @CNPJ)
END;


CREATE OR ALTER PROC InserirPF @nm varchar(30), @cpf varchar(14), @dtc datetime, @tel varchar(13), @rg varchar(9), @nasc date, @fkEmp int AS BEGIN
INSERT INTO dbo.FORN_PF (NOME,CPF,DATA_CADASTRO,TELEFONE,RG,NASCIMENTO,FK_EMP) VALUES (@nm, @cpf, @dtc, @tel, @rg, @nasc, @fkEmp)
END;


CREATE OR ALTER PROC InserirPJ @nm varchar(30), @cpj varchar(14), @dtc datetime, @tel varchar(13), @fkEmp int AS BEGIN
INSERT INTO dbo.FORN_PJ (NOMEFANTASIA,CNPJ,DATA_CADASTRO,TELEFONE, FK_EMP) VALUES (@nm, @cpj, @dtc, @tel, @fkEmp)
END;


CREATE OR ALTER PROC InserirTelAdd @tel varchar(13), @FkPj int, @FkPf int AS BEGIN
INSERT INTO TELEFONES_ADICIONAIS (TELEFONE,FK_PJ,FK_PF) VALUES (@tel, @FkPj, @FkPf)
END;

