
/*empresa do paraná */
CREATE TABLE EMPRESA
(
	ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	UF VARCHAR(3) NOT NULL,
	NOMEFANTASIA VARCHAR(100) NOT NULL,
	CNPJ VARCHAR(14) NOT NULL,
	CONSTRAINT CadastroMultiplo UNIQUE (CNPJ)	
);

CREATE TABLE FORN_PJ
(
	ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	NOMEFANTASIA VARCHAR(100) NOT NULL,
	CNPJ VARCHAR(14) NOT NULL,
	DATA_CADASTRO DATETIME,
	TELEFONE VARCHAR (13) NOT NULL,
	CONSTRAINT CadastroPjMultiplo UNIQUE (CNPJ),
	FK_EMP INT NOT NULL	FOREIGN KEY REFERENCES EMPRESA(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE FORN_PF
(
	ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	DATA_CADASTRO DATETIME,
	TELEFONE VARCHAR (13) NOT NULL,
	RG VARCHAR(9),
	NASCIMENTO DATE,
	CONSTRAINT CadastroPfMultiplo UNIQUE (CPF),
	FK_EMP INT NOT NULL	FOREIGN KEY REFERENCES EMPRESA(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE TELEFONES_ADICIONAIS
(
	ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	TELEFONE VARCHAR (13) NOT NULL,
	CONSTRAINT TelefoneExistente UNIQUE (TELEFONE),
	FK_PJ INT FOREIGN KEY REFERENCES FORN_PJ(ID),
	FK_PF INT FOREIGN KEY REFERENCES FORN_PF(ID)
);

/* ------------------------ COMANDOS ------------------------ */

SELECT * FROM dbo.EMPRESA;

SELECT PF.ID,
	   PF.NOME,
	   PF.CPF,
	   PF.DATA_CADASTRO,
	   PF.RG,
	   PF.NASCIMENTO,
	   PF.TELEFONE,
	   TAD.TELEFONE AS TF_ADICIONAIS
	   FROM dbo.FORN_PF AS PF
	   INNER JOIN dbo.EMPRESA AS EMP ON FK_EMP = EMP.ID
	   INNER JOIN dbo.TELEFONES_ADICIONAIS AS TAD ON TAD.FK_PF = PF.ID;


SELECT PF.ID,
	   PF.NOME,
	   PF.TELEFONE,
	   TAD.TELEFONE AS TF_ADICIONAIS
	   FROM dbo.FORN_PF AS PF
	   INNER JOIN dbo.EMPRESA AS EMP ON FK_EMP = EMP.ID
	   INNER JOIN dbo.TELEFONES_ADICIONAIS AS TAD ON TAD.FK_PF = PF.ID;

SELECT * FROM dbo.TELEFONES_ADICIONAIS;


